vetFrutas = ["ABACATE", "ABACAXI", "ABIU", "ABRICÓ", "ABRUNHO", "AÇAÍ", "ACEROLA", "AKEE", "ALFARROBA", "AMEIXA", "AMÊNDOA", "AMORA", "ANANÁS", "ANONA", "ARAÇÁ", "ARANDO", "ARATICUM", "ATA", "ATEMOIA", "AVELÃ", "BABACO", "BABAÇU", "BACABA", "BACURI", "BACUPARI", "BANANA", "BARU", "BERGAMOTA", "BIRIBÁ", "BURITI", "BUTIÁ", "CABELUDINHA", "CACAU", "CAGAITA", "CAIMITO", "CAJÁ", "CAJU", "CALABAÇA", "CALABURA", "CALAMONDIN", "CAMBUCÁ", "CAMBUCI", "CAMU-CAMU", "CAQUI", "CARAMBOLA", "CARNAÚBA", "CASTANHA", "CASTANHA-DO-PARÁ", "CEREJA", "CIRIGUELA", "CIRUELA", "COCO", "CRANBERRY", "CUPUAÇU", "DAMASCO", "DEKOPON", "DENDÊ", "DIÓSPIRO", "DOVYALIS", "DURIÃO", "EMBAÚBA", "EMBAUBARANA", "ENGKALA", "ESCROPARI", "ESFREGADINHA", "ESPORÃO-DE-GALO", "FIGO", "FRAMBOESA", "FRUTA-DO-CONDE", "FRUTA-PÃO", "FEIJOA", "FIGO-DA-ÍNDIA", "FRUTA-DE-CEDRO", "FRUTA-DE-LOBO", "FRUTA-DO-MILAGRE", "FRUTA-DE-TATU", "GABIROBA", "GLICOSMIS", "GOIABA", "GRANADILLA", "GRAVATÁ", "GRAVIOLA", "GROSELHA", "GRUMIXAMA", "GUABIJU", "GUABIROBA", "GUARANÁ", "HAWTHORN", "HEISTERIA", "HILOCÉREO", "IBACURUPARI", "ILAMA", "IMBE", "IMBU", "INAJÁ", "INGÁ", "INHARÉ", "JABUTICABA", "JACA", "JAMBO", "JAMBOLÃO", "JAMELÃO", "JARACATIÁ", "JATOBÁ", "JENIPAPO", "JERIVÁ", "JUÁ", "JUJUBA", "KIWI", "KUMQUAT", "KINKAN", "KINO", "KIWANO", "KABOSU", "KARITÉ", "KORLAN", "LARANJA", "LIMÃO", "LIMA", "LICHIA", "LONGAN", "LUCUMA", "LACUCHA", "LULO", "LOBEIRA", "LANGSAT", "LARANJA-DE-PACU", "MABOLO", "MAÇÃ", "MACADÂMIA", "MACAÚBA", "MAMÃO", "MAMEY", "MAMONCILLO", "MANÁ-CUBIU", "MANGA", "MANGABA", "MANGOSTÃO", "MARACUJÁ", "MARANG", "MARMELO", "MAROLO", "MARULA", "MASSALA", "MELANCIA", "MELÃO", "MELOA", "MEXERICA", "MIRTILO", "MORANGO", "MURICI", "NARANJILLA", "NECTARINA", "NÊSPERA", "NONI", "NOZ", "NOZ-PECÃ", "NOZ-MACADÂMIA", "OITI", "OXICOCO", "ORANGELO", "PERA", "PÊSSEGO", "PITANGA", "PINHA", "PITAIA", "PITOMBA", "PITANGATUBA", "PINDAÍBA", "PEQUI", "PEQUIÁ", "PHYSALIS", "PULASAN", "POMELO", "PUPUNHA", "PUÇÁ", "PATAUÁ", "PAJURÁ", "PIXIRICA", "PISTACHE", "QUINA", "QUIUÍ", "QUIXABEIRA", "ROMÃ", "RAMBAI", "RAMBUTÃO", "RUKAM", "SAGUARAJI", "SALAK", "SANTOL", "SAPOTA", "SAPOTI", "SAPUCAIA", "SAPUTÁ", "SERIGUELA", "SORVINHA", "TANGERINA", "TAMARINDO", "TÂMARA", "TORANJA", "TUCUMÃ", "TAIUVA", "TAPIÁ", "TARUMÃ", "TANGOR", "TUCUJÁ", "UVA", "UMBU", "UVAIA", "UCHUVA", "UMÊ", "UXI", "UCUUBA", "VACÍNIO", "VELUDO", "VERGAMOTA", "VELUDO-BRANCO", "WAMPI", "XIXÁ", "YAMAMOMO", "YUZU", "ZIMBRO",
"ABACATES", "ABACAXIS", "ABIUS", "ABRICÓS", "ABRUNHOS", "AÇAÍS", "ACEROLAS", "AKEES", "ALFARROBAS", "AMEIXAS","AMÊNDOAS", "AMORAS", "ANANASES", "ANONAS", "ARAÇÁS", "ARANDOS", "ARATICUNS", "ATAS", "ATEMOIAS", "AVELÃS",
"BABACOS", "BABAÇUS", "BACABAS", "BACURIS", "BACUPARIS", "BANANAS", "BARUS", "BERGAMOTAS", "BIRIBÁS", "BURITIS","BUTIÁS", "CABELUDINHAS", "CACAUS", "CAGAITAS", "CAIMITOS", "CAJÁS", "CAJUS", "CALABAÇAS", "CALABURAS", "CALAMONDINS","CAMBUCÁS", "CAMBUCIS", "CAMU-CAMUS", "CAQUIS", "CARAMBOLAS", "CARNAÚBAS", "CASTANHAS", "CASTANHAS-DO-PARÁ", "CEREJAS","CIRIGUELAS", "CIRUELAS", "COCOS", "CRANBERRIES", "CUPUAÇUS", "DAMASCOS", "DEKOPONS", "DENDÊS", "DIÓSPIROS", "DOVYALIS","DURIÕES", "EMBAÚBAS", "EMBAUBARANAS", "ENGKALAS", "ESCROPARIS", "ESFREGADINHAS", "ESPORÕES-DE-GALO", "FIGOS", "FRAMBOESAS","FRUTAS-DO-CONDE", "FRUTAS-PÃO", "FEIJOAS", "FIGOS-DA-ÍNDIA", "FRUTAS-DE-CEDRO", "FRUTAS-DE-LOBO", "FRUTAS-DO-MILAGRE","FRUTAS-DE-TATU", "GABIROBAS", "GLICOSMIS", "GOIABAS", "GRANADILLAS", "GRAVATÁS", "GRAVIOLAS", "GROSELHAS", "GRUMIXAMAS","GUABIJUS", "GUABIROBAS", "GUARANÁS", "HAWTHORNS", "HEISTERIAS", "HILOCÉREOS", "IBACURUPARIS", "ILAMAS", "IMBES", "IMBUS","INAJÁS", "INGÁS", "INHARÉS", "JABUTICABAS", "JACAS", "JAMBOS", "JAMBOLÕES", "JAMELÕES", "JARACATIÁS", "JATOBÁS","JENIPAPOS", "JERIVÁS", "JUÁS", "JUJUBAS", "KIWIS", "KUMQUATS", "KINKANS", "KINOS", "KIWANOS", "KABOSU", "KARITÉS","KORLANS", "LARANJAS", "LIMÕES", "LIMAS", "LICHIAS", "LONGANS", "LUCUMAS", "LACUCHAS", "LULOS", "LOBEIRAS", "LANGSATS","LARANJAS-DE-PACU", "MABOLOS", "MAÇÃS", "MACADÂMIAS", "MACAÚBAS", "MAMÕES", "MAMEYS", "MAMONCILLOS", "MANÁ-CUBIUS","MANGAS", "MANGABAS", "MANGOSTÃOS", "MARACUJÁS", "MARANGS", "MARMELOS", "MAROLOS", "MARULAS", "MASSALAS", "MELANCIAS","MELÕES", "MELOAS", "MEXERICAS", "MIRTILOS", "MORANGOS", "MURICIS", "NARANJILLAS", "NECTARINAS", "NÊSPERAS", "NONIS","NOZES", "NOZES-PECÃ", "NOZES-MACADÂMIAS", "OITIS", "OXICOCOS", "ORANGELOS", "PERAS", "PÊSSEGOS", "PITANGAS", "PINHAS","PITAIAS", "PITOMBAS", "PITANGATUBAS", "PINDAÍBAS", "PEQUIS", "PEQUIÁS", "PHYSALIS", "PULASANS", "POMELOS", "PUPUNHAS","PUÇÁS", "PATAUÁS", "PAJURÁS", "PIXIRICAS", "PISTACHES", "QUINAS", "QUIUÍS", "QUIXABEIRAS", "ROMÃS", "RAMBAIS","RAMBUTÕES", "RUKAMS", "SAGUARAJIS", "SALAKS", "SANTOLS", "SAPOTAS", "SAPOTIS", "SAPUCAIAS", "SAPUTÁS", "SERIGUELAS","SORVINHAS", "TANGERINAS", "TAMARINDOS", "TÂMARAS", "TORANJAS", "TUCUMÃS", "TAIUVA", "TAPIÁS", "TARUMÃS", "TANGORES","TUCUJÁS", "UVAS", "UMBUS", "UVAIAS", "UCHUVAS", "UMÊS", "UXIS", "UCUUBAS", "VACÍNIOS", "VELUDOS", "VERGAMOTAS","VELUDOS-BRANCOS", "WAMPIS", "XIXÁS", "YAMAMOMOS", "YUZUS", "ZIMBROS"];
vetLegumes = ["ABÓBORA", "ABOBRINHA", "AIPIM", "ALHO", "AMARANTO", "AMÊNDOA", "AMENDOIM", "AMENDOIM-DA-MATA", "ANDU", "ARACHACHÁ", "ARROZ", "ARROZ-SELVAGEM", "AVEIA", "AVELÃ", "AZEITONA", "BAROA", "BATATA", "BATATA-DOCE", "BERDANA", "BERINJELA", "BETERRABA", "CABOTCHAN", "CARÁ", "CARÁ-DO-AR", "CARÁ-MOELA", "CASTANHA-DE-BARU", "CASTANHA-DE-CAJU", "CASTANHA-DE-MACACO", "CASTANHA-DO-MARANHÃO", "CASTANHA-DO-PARÁ", "CASTANHEIRO-DO-MATO", "CAXI", "CEBOLA", "CELÓSIA", "CENOURA", "CENTEIO", "CEVADA", "CHALOTA", "CHIA", "CHICHÁ", "CHICHÁ-DO-NORTE", "CHUCHU", "COUVE-NABO", "COUVE-RÁBANO", "CUMARU", "DENDÊ", "ERVILHA", "ERVILHA-DE-POMBO", "ESCORCIONEIRA", "FAVA", "FEIJÃO", "FEIJÃO-ANDU", "FEIJÃO-AZUKI", "FEIJÃO-BOER", "FRUTA-PÃO", "GENGIBRE", "GERGELIM", "GIRASSOL", "GOBÔ", "GOYA", "GRÃO-DE-BICO", "GRUMIXAMA", "GUANDU", "INAJÁ", "INHAME", "JACA VERDE", "JALAPEÑO", "JICAMA", "JILÓ", "KOHLRABI", "LABACA", "LENTILHA", "LINHAÇA", "LÍRIO-DO-BREJO", "MACASSÁ", "MALAGUETA", "MALTE", "MANDIOCA", "MANDIOQUINHA", "MAXIXE", "MENDUBIGUAÇU", "MILHO", "MITSUBÁ", "MOGANGO", "MONGUBA", "MORANGA", "NABO", "NABO-DA-SUÉCIA", "NABO-MEXICANO", "NABO-SUECO", "NOZ", "NOZES-DA-MACADÂMIA", "OLIVA", "PALMITO", "PARU", "PAU-REI", "PÉ-DE-ANTA", "PELEGA", "PEPINO", "PEPINO-JAPONÊS", "PEQUI", "PIMENTA", "PIMENTÃO", "PINHÃO", "PISTACHE", "QUIABO", "QUINOA", "RABANETE", "RÁBANO", "RÁBANO-SILVESTRE", "RAIZ-FORTE", "RUTABAGA", "SHISSÔ", "SOJA", "SORGO", "TAIOBA", "TARO", "TOMATE", "TOMATE-CEREJA", "TONKA", "TRIGO", "TUPINAMBO", "URUCUM", "VAGEM", "WASABI", "XIXÁ", "XOCONOSTLE", "ZIZÂNIA", "ABÓBORAS", "ABOBRINHAS", "AIPINS", "ALHOS", "AMARANTOS", "AMÊNDOAS", "AMENDOINS", "AMENDOINS-DA-MATA", "ANDUS", "ARACHACHÁS",
"ARROZES", "ARROZ-SELVAGENS", "AVEIAS", "AVELÃS", "AZEITONAS", "BAROAS", "BATATAS", "BATATAS-DOCES", "BERDANAS", "BERINJELAS","BETERRABAS", "CABOTCHANS", "CARÁS", "CARÁS-DO-AR", "CARÁS-MOELA", "CASTANHAS-DE-BARU", "CASTANHAS-DE-CAJU", "CASTANHAS-DE-MACACO","CASTANHAS-DO-MARANHÃO", "CASTANHAS-DO-PARÁ", "CASTANHEIROS-DO-MATO", "CAXIS", "CEBOLAS", "CELÓSIAS", "CENOURAS", "CENTEIOS","CEVADAS", "CHALOTAS", "CHIAS", "CHICHÁS", "CHICHÁS-DO-NORTE", "CHUCHUS", "COUVES-NABO", "COUVES-RÁBANO", "CUMARUS", "DENDÊS","ERVILHAS", "ERVILHAS-DE-POMBO", "ESCORCIONEIRAS", "FAVAS", "FEIJÕES", "FEIJÕES-ANDU", "FEIJÕES-AZUKI", "FEIJÕES-BOER", "FRUTAS-PÃO","GENGIBRES", "GERGELINS", "GIRASSÓIS", "GOBÔS", "GOYAS", "GRÃOS-DE-BICO", "GRUMIXAMAS", "GUANDUS", "INAJÁS", "INHAMES","JACAS VERDES", "JALAPEÑOS", "JICAMAS", "JILÓS", "KOHLRABIS", "LABACAS", "LENTILHAS", "LINHAÇAS", "LÍRIOS-DO-BREJO", "MACASSÁS","MALAGUETAS", "MALTES", "MANDIOCAS", "MANDIOQUINHAS", "MAXIXES", "MENDUBIGUAÇUS", "MILHOS", "MITSUBÁS", "MOGANGOS", "MONGUBAS","MORANGAS", "NABOS", "NABOS-DA-SUÉCIA", "NABOS-MEXICANOS", "NABOS-SUECOS", "NOZES", "NOZES-DA-MACADÂMIA", "OLIVAS", "PALMITOS","PARUS", "PAUS-REI", "PÉS-DE-ANTA", "PELEGAS", "PEPINOS", "PEPINOS-JAPONÊSES", "PEQUIS", "PIMENTAS", "PIMENTÕES", "PINHÕES","PISTACHES", "QUIABOS", "QUINOAS", "RABANETES", "RÁBANOS", "RÁBANOS-SILVESTRES", "RAÍZES-FORTES", "RUTABAGAS", "SHISSÔS","SOJAS", "SORGOS", "TAIOBAS", "TAROS", "TOMATES", "TOMATES-CEREJA", "TONKAS", "TRIGOS", "TUPINAMBOS", "URUCUNS", "VAGENS", "WASABIS", "XIXÁS", "XOCONOSTLES", "ZIZÂNIAS"];

textoOriginal = prompt(`Insira um texto legal falando sobre seus alimentos saudáveis!`);
texto = textoOriginal;

texto = texto.replaceAll(")", "");
texto = texto.replaceAll("(", "");
texto = texto.replaceAll("_", "");
texto = texto.replaceAll("-", "");
texto = texto.replaceAll("!", "");
texto = texto.replaceAll("?", "");
texto = texto.replaceAll(".", "");
texto = texto.replaceAll(";", "");
texto = texto.replaceAll(":", "");
texto = texto.replaceAll('"', "");
texto = texto.replaceAll("'", "");
texto = texto.replaceAll(',', "");

textoSeparado = texto.toUpperCase()
textoSeparado = textoSeparado.split(" ");

frutasTexto = [];
legumesTexto = [];

for (i = 0; i < textoSeparado.length; i++) {
    if (vetFrutas.includes(textoSeparado[i])) {
        frutasTexto.push(textoSeparado[i].toLowerCase());
    }
    else if (vetLegumes.includes(textoSeparado[i])) {
        legumesTexto.push(textoSeparado[i].toLowerCase());
    }
}

frasesSeparadas = textoOriginal.replaceAll('"', "");
frasesSeparadas = frasesSeparadas.replaceAll('!', ".");
frasesSeparadas = frasesSeparadas.replaceAll('?', ".");
frasesSeparadas = frasesSeparadas.split(".");


document.write(`
    <h1>Frutas contidas no texto: ${frutasTexto.length}</h1>
    <p>${frutasTexto}</p>
    <h1>Verduras contidas no texto: ${legumesTexto.length}</h1>
    <p>${legumesTexto}</p>
    <hr>
`)
document.write(`
    <h2>Estatísticas</h2>
    <p><b>Texto original:</b> ${textoOriginal}</p>
    <p><b>Total (palavras analisadas):</b> ${textoSeparado.length}</p>
    <p><b>Frases:</b></p>
    <ul>
`)

for (i = 0; i < frasesSeparadas.length - 1; i++) {
    document.write(`<li>${frasesSeparadas[i].trim()}</li>`)
}
document.write(`
    </ul>
    <p><b>Total de frases:</b> ${frasesSeparadas.length - 1}</p>
`)